config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  # get '/visualisation', to: 'map#visualisation', as: 'visualisations'
  # get '/visualisation/:folder_id', to: 'map#visualisation', as: 'visualisation'

  # get 'visualisation/data_folder/:folder_id', to: 'map#data'
  # get '/data', to: 'map#data', as: 'data'

  post '/auth', to: 'pages#auth'
  get '/checkauth', to: 'pages#check_auth'
  get '/signout', to: 'pages#signout'

  get '/folders/folders_name', to: 'folders#send_folders_name'
  post 'tabs/assign_folder', to: 'tabs#assign_folder_to_tabs'
  get 'tabs/order-by-dates', to: 'tabs#index_by_date', as: 'filtered_by_date'

  get 'folders/search', to: 'folders#search', as: 'search'

  resources :folders, only: [:update, :index, :show, :destroy, :edit]
  resources :tabs, only: [:edit, :create, :destroy]
  resources :blacklisted_sites, only: [:index, :new, :create, :destroy]

  root to: "pages#landing"
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: 'Folder', optional: true
  has_many :folders, foreign_key: :parent_id
  has_many :tabs

  validates :name, uniqueness: { scope: :user }, presence: true
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  # skip_before_action :authenticate_user!
  before_action :set_folder, only: [:show, :destroy, :update]
  before_action :folders_to_display, only: [:index, :send_folders_name]

  def index
    @folders = @folders.sort_by { |folder| folder.tabs.last.id }.reverse
    @tabs = []
    @folders.reverse.each do |folder|
      @tabs << folder.tabs
    end
  end

  def search
    @tabs = current_user.tabs
    @query_tabs = @tabs.search_in_description(params[:query])
    @query_tabs.to_a.uniq! { |tab| tab.url }
    query_array = params[:query].downcase.split(' ')
    if query_array.length > 1
      @key_word = query_array[0]
    else
      @key_word = params[:query]
    end
  end

  def update
    if @folder.update(folder_params)

      redirect_to folders_path
    else
      render :edit
    end
  end

  def destroy
    @folder.tabs.each(&:destroy)
    @folder.destroy
    redirect_to folders_path
  end

  def send_folders_name
    folders_json = []
    @folders.each do |folder|
      folders_json << {
        name: folder.name.to_s,
        id: folder.id.to_s
      }
    end
    render json: folders_json
  end

  private

  def set_folder
    @folder = Folder.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:name, :weight, :parent_id)
  end

  def folders_to_display
    @folders = current_user.folders.where.not(name: 'My researches')
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_modal.html.erb
<div class="background-modal background-tab-modal">
	<div class="confirm-modal">
		<div class="confirm-modal-content">
			<p>Are you sure you want to delete this tab?</p>
			<div class="modal-buttons">
				<div class="yes-btn yes-btn-tab modal-btn"></div>
				<div class="no-btn modal-btn">No</div>
			</div>
		</div>
	</div>
</div>

<div class="background-modal background-folder-modal">
	<div class="confirm-modal">
		<div class="confirm-modal-content">
			<p>Are you sure you want to delete this research?</p>
			<div class="modal-buttons">
				<div class="yes-btn yes-btn-folder modal-btn"></div>
				<div class="no-btn modal-btn hover-black">No</div>
			</div>
		</div>
	</div>
</div>

app/views/folders/edit.html.erb
<div class="nav-links">
  <%= link_to '< Back', folders_path %>
</div>

<div class="form-container">
  <h1 id="form-title">Editing folder</h1>

   <% array = [nil] %>
   <%  @parantfolder.each do |fp| %>
     <% array << fp.id %>
   <% end %>


  <%= simple_form_for(@folder) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <div class="categories-button">
    <%= f.input :weight, as: :radio_buttons, collection: [1, 2, 3], wrapper: false %>
    </div>
    <div class="categories-button">
    <%= f.input :parent_id, as: :radio_buttons, collection: array, wrapper: false %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, id: "submit-button", class: "btn btn-secondary"%>
   </div>
<% end %>
</div>

app/views/folders/index.html.erb
<%= render "layouts/searchbar" %>

<div class="links-buttons">
  <div>
    <%= link_to 'Folders', folders_path, class: "folders-link active" %>
  </div>
  <div>
    <%= link_to 'By Dates', filtered_by_date_path, class: "by-dates-link" %>
  </div>
</div>

<div class="user-search" id="pagesindex">
  <% @folders.each do |folder| %>

    <details class="user-search-folder-content" id= "div-folder-<%= folder.id %>">

      <summary class="user-search-header">
        <div class='user-search-header-content'>
          <h3 class="user-search-title">
            <%= simple_form_for([ folder ], remote: true) do |form| %>
              <%= form.input :name , label: false, input_html: { "data-folder" => folder.id } %>
              <%= form.button :submit,  id: "idFolder-#{folder.id}" , value: "Update", type: "hidden", class: 'bnt btnTitreFolder' %>
            <% end %>
          </h3>
          <h4 class="tabs-number"><%= pluralize(folder.tabs.count, "tab") %></h4>
        </div>
        <%= link_to 'Open All', '', class: 'primary-button open-tabs' , :"data-tabs" => folder.tabs.to_json %>
        <div class="btnremove btn fas fa-times" data-folderid=<%= folder.id %> ></div>
      </summary>

      <div class="cards-container-display display-cards" id="idfolder-${folder.id}">
        <% folder.tabs.each do |tab| %>
          <div class="tab-card" data-tabid="<%= tab.id %>">
            <img src="<%= tab.icon.nil? ? "http://imageshack.com/a/img924/7323/nbroSO.png" : tab.icon %>" class="icon-tab">
            <div class="tab-card-content" data-taburl="<%= tab.url.to_json %>">
              <a href="<%= tab.url %>" class="tab-url" target="_blank">
                <p class="tab-name"><%= tab.name %></p>
                <p class="tab-title"><%= URI.decode(tab.title) %></p>
              </a>
              <div class="delete-icon fas fa-times" data-tabid=<%= tab.id %>></div>
            </div>
          </div>
        <% end %>
      </div>

    </details>

  <% end %>
</div>

<%= render "modal" %>

app/views/folders/search.html.erb
<%= render "layouts/searchbar" %>

<h1>Results for " <%= params[:query] %> "</h1>
<div class="results-cards-container">
  <% @query_tabs.each do |tab| %>
    <div class="results-tab-card" id="<%= tab.id %>">
      <div class="results-tab-card-header-container">
      
        <img src="<%= tab.icon.nil? ? "http://imageshack.com/a/img924/7323/nbroSO.png" : tab.icon %>" class="avatar">
        <div class="tab-card-header tab-card-content">
          <a href="<%= tab.url %>" class="tab-link" target="_blank">
            <h3 class="tab-name"><%= tab.name %></h3>
            <p class="tab-title"><%= URI.decode(tab.title) %></p>
          </a>
        </div>
      </div>
      <div class="tab-body-description">
        <ul>
          <% results_sentences = tab.description.downcase.scan(/\w.{0,50}#{@key_word}.{0,60}/) %>
          <% results_sentences.uniq.each do |sentence| %>
            <% sentence = sentence.gsub(@key_word,"<strong>#{@key_word}</strong>") %>
            <li>« ... <%= sentence.html_safe %> ... »</li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/folders/show.html.erb
<% content_for :meta_title, "My search #{@folder.name} on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_image, image_path("singletab_white_black.png") %>

<div  class="containershow">
<h2><%= @folder.name %></h2>
<a class="fas fa-chart-bar ml-3" href="/visualisation/<%= @folder.id %>">Show map</a>
<a  class="fas fa-external-link-alt openAllLink" href="">Open all</a>

<% if @folder.folders != nil %> <!-- si le folder a un ou des enfants -->
  <% @folder.folders.each do |folder| %>
    <h3><%= folder.name %></h3> <!-- afficher le nom de chaque folder -->

    <h6>Tabs : </h6>
    <% @folder.tabs.each do |tab| %>
      <p><%= tab.name %></p> <!-- dans chaque folder, afficher chacune des tabs contenues -->
      <a href="<%= tab.url %>" class="btn" >Open</a>
    <% end %>
  <% end %>
<% end %>
<br>
<% @folder.tabs.each do |tab| %> <!-- si le folder parent (=la map) a des tabs sans folders enfants attitrés, ils sont affichés aussi -->
  <p><%= tab.url %></p>
  <p><%= tab.title %></p>
  <img src="<%= tab.icon %>" alt="">
<% end %>

<div id="showfold" data-folders="<%= @folder.attributes.merge({tabs: @folder.tabs}).to_json
 %>" data-tabs="<%= @folder.tabs.to_json %>"></div>

</div>