config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  # get '/visualisation', to: 'map#visualisation', as: 'visualisations'
  # get '/visualisation/:folder_id', to: 'map#visualisation', as: 'visualisation'

  # get 'visualisation/data_folder/:folder_id', to: 'map#data'
  # get '/data', to: 'map#data', as: 'data'

  post '/auth', to: 'pages#auth'
  get '/checkauth', to: 'pages#check_auth'
  get '/signout', to: 'pages#signout'

  get '/folders/folders_name', to: 'folders#send_folders_name'
  post 'tabs/assign_folder', to: 'tabs#assign_folder_to_tabs'
  get 'tabs/order-by-dates', to: 'tabs#index_by_date', as: 'filtered_by_date'

  get 'folders/search', to: 'folders#search', as: 'search'

  resources :folders, only: [:update, :index, :show, :destroy, :edit]
  resources :tabs, only: [:edit, :create, :destroy]
  resources :blacklisted_sites, only: [:index, :new, :create, :destroy]

  root to: "pages#landing"
end

app/views/layouts/_footer.html.erb
<div class="footer">
      <div class="footer-links">
        <img src="https://ca.slack-edge.com/T02NE0241-UNY9A8GKG-b39faa461717-512" alt="Marco" class="team-mate">
        <img src="https://ca.slack-edge.com/T02NE0241-UNH4MDCGJ-0ee61023eedd-512" alt="Eric" class="team-mate">
        <img src="https://avatars0.githubusercontent.com/u/53219631?v=4" alt="Jojo" class="team-mate">
      </div>
      <div class="footer-copyright">
        SingleTab is a project developped with a lot of alcool <i class="fas fa-beer"></i> Enjoy!
      </div>
    </div>

app/views/layouts/_navbar.html.erb
<header class="header">
  <nav class="navbar">
    <div class="wrapper">
      <span><a class="logo" href="https://www.singletab.site"><%= image_tag("singletab_black_and_white.png") %></a></span>
      <a href="https://www.singletab.site" class="url-title-singletab"><h1 class="title-singletab">SINGLETAB</h1></a>
      <ul class="menu">
        <li><%= link_to 'HOME', folders_path, class: 'menu-link' %></li>
        <li><%= link_to 'SETTINGS', new_blacklisted_site_path, class: 'menu-link' %></li>
        <li><a class="menu-link" href="#">FAQ</a></li>
        <li><a class="menu-link" href="#">CONTACT</a></li>
        <li><%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'menu-link') %></li>
      </ul>
    </div>
    <div class="toggle">
      <div class="span span-one"></div>
      <div class="span span-two"></div>
      <div class="span span-three"></div>
    </div>
  </nav>
  <div class="mobile">
    <ul class="menu">
      <li class="menu-item">
        <%= link_to 'HOME', folders_path, class: 'menu-link' %>
      </li>
      <li class="menu-item">
        <a class="menu-link" href="#">FAQ</a>
      </li>
      <li class="menu-item">
        <a class="menu-link" href="#">CONTACT</a>
      </li>
      <li class="menu-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'menu-link') %>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/_searchbar.html.erb
<%= simple_form_for :search, url: search_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input autofocus class="form-control string required" type="text" name="query" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i><p>Search</p>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-158889049-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-158889049-1');
    </script>

    <title>SingleTab | All your searches in one single tab</title>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">


    <!-- Favicon generator -->
    <%= favicon_link_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="https://imageshack.com/a/img924/5879/AT9SZi.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body class="<%= body_class %>">
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' unless @disable_nav %>
    <% end %>

    <div class="container">

      <%= yield %>

    <% unless notice.nil? %>
      <p class="notice fadeOut"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="alert fadeOut"><%= alert %></p>
    <% end %>

    </div>

    <%= render 'layouts/footer' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>